-- Схема общей базы посещаемости для Supabase.
-- Выполните этот файл целиком в Supabase Dashboard -> SQL Editor.

create table if not exists public.members (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists public.attendance (
    date date not null,
    member_id bigint not null references public.members(id) on delete cascade,
    status text not null check (status in ('present', 'absent', 'valid_absent')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (date, member_id)
);

create table if not exists public.settings (
    key text primary key,
    value text not null,
    updated_at timestamptz not null default now()
);

insert into public.settings (key, value)
values ('visitor_password', 'KDKR1105')
on conflict (key) do nothing;

alter table public.members enable row level security;
alter table public.attendance enable row level security;
alter table public.settings enable row level security;

-- Посетители могут видеть общий список и общую посещаемость.
drop policy if exists "public read members" on public.members;
create policy "public read members"
    on public.members for select
    to anon, authenticated
    using (true);

drop policy if exists "public read attendance" on public.attendance;
create policy "public read attendance"
    on public.attendance for select
    to anon, authenticated
    using (true);

drop policy if exists "public read visitor password setting" on public.settings;
create policy "public read visitor password setting"
    on public.settings for select
    to anon, authenticated
    using (key = 'visitor_password');

-- ВНИМАНИЕ: эти политики разрешают запись анонимным посетителям,
-- потому что текущая версия приложения использует пароль в браузере.
-- Для настоящей защиты администратора замените их Supabase Auth + Edge Function.
drop policy if exists "public insert members" on public.members;
create policy "public insert members"
    on public.members for insert
    to anon, authenticated
    with check (true);

drop policy if exists "public update members" on public.members;
create policy "public update members"
    on public.members for update
    to anon, authenticated
    using (true)
    with check (true);

drop policy if exists "public delete members" on public.members;
create policy "public delete members"
    on public.members for delete
    to anon, authenticated
    using (true);

drop policy if exists "public insert attendance" on public.attendance;
create policy "public insert attendance"
    on public.attendance for insert
    to anon, authenticated
    with check (true);

drop policy if exists "public update attendance" on public.attendance;
create policy "public update attendance"
    on public.attendance for update
    to anon, authenticated
    using (true)
    with check (true);

drop policy if exists "public delete attendance" on public.attendance;
create policy "public delete attendance"
    on public.attendance for delete
    to anon, authenticated
    using (true);

-- Менять settings через браузер нельзя: текущий пароль посетителя
-- должен изменяться только после добавления серверной админской функции.
drop policy if exists "public update visitor setting" on public.settings;
